web:
  image: cmelion/generator-redux-observable:latest
  volumes:
    - ./README.md:/home/yeoman/client/README.md
    - ./package.json:/home/yeoman/client/package.json
    - ./src:/home/yeoman/client/src
    - ./json-server:/home/yeoman/client/json-server
  ports:
    - "2368:2368"
    - "3000:3000"